<a href="https://colab.research.google.com/github/futureCodersSE/python-programming-for-data/blob/main/Worksheets/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Using numpy for processing arrays and matrices of number data

---

## numpy is a more efficient number array processing library for Python

Python lists can contain any type of data, including objects.  numpy arrays are **specialised and can only contain numbers**.  They are especially useful in data analysis for holding quantitive data series for correlation and visualisation.

You can customise the memory usage so that arrays can use less memory and items are stored contiguously.  This means that it is **more efficient/faster processing large data sets**.

Use numpy arrays to **store and manipulate large lists of numbers** (for other data types use plain Python lists or a panda series)

Where a pandas column (series) is large and contains numerical data, converting it to a numpy array will help with performance.


---
### Creating a numpy array from a Python list

To use numpy, you will need to import it.  The conventional way to import numpy is to import the whole library and use an *alias*

`import numpy as np`

Every time you want to use a function from the numpy library you use the syntax:  
`np.function_name()`  

Create a new numpy array from a Python list of numbers
   
`arr = np.array([1,2,3])`

Or a new numpy matrix from a Python 2 dimensional list of numbers

`matrix = np.array([1,2,3],[4,5,6])`

***Reference***:  https://numpy.org/doc/stable/reference/index.html

---
### Exercise 1 - create a numpy array from a given list  

Write a function called `make_array(num_list`) which will:
*   accept num_list as a parameter  
*   create a new numpy array called **new_array** from `num_list`
*   return `new_array`

Test input:  
`num_list = [3,6,2,5,8,6]`  

Expected output:  
`[3 6 2 5 8 6] ` 



In [ ]:
import numpy as np

def make_array(num_list):
  # add code below here to create a numpy array called new_array from num_list



# run make_array with the list [3,6,2,5,8,6]
list_to_convert = [3,6,2,5,8,6]
actual = make_array(list_to_convert)
print(actual)

## Setting the number type in memory

numpy allows you to set the type of number in memory (e.g. `int8`, `int32`) when you create the array.  This allows memory allocation to be as small as possible.  

`new_matrix = np.array([[1, 2, 3], [4, 5, 6]], np.int8)`    

This creates a two row, three column matrix of whole numbers which are all small enough to fit in 1 byte of memory storage.

---
### Exercise 2 - create matrix of smallish numbers

Write a function which will:
*   accept a parameter **num_2d_list** which will be a 2-dimensional list  
*   create a new numpy array called **create_new_matrix** from `num_2d_list`, with data size `int16`
*   return `new_matrix[0]`, `new_matrix[1]`

Test input:  
`[[31112, 32321, 24567],[456,324,789]]`

Expected output:   
```
[31112 32321 24567] [456 324 789]
```

In [ ]:
import numpy as np

def create_new_matrix(num_2d_list):
  # add code below here to create a numparray from num_2d_list with data size 'int16'



# run create_new_matrix with the list [[31112, 32321, 24567],[456,324,789]]
matrix_to_convert = [[31112, 32321, 24567],[456,324,789]]
first_row, second_row = create_new_matrix(matrix_to_convert)
print(first_row, second_row)

---
### Exercise 3 - make a 3 x 3 numpy array

Write a function which  will create a 3 x 3 array, and print the array one row per line.  The function should then return the array

Test data:  
`[[1,2,3],[4,5,6],[7,8,9]]`

Expected output:  
```
[1 2 3]
[4 5 6]  
[7 8 9]
```
  

In [ ]:
import numpy as np

def # write the function header to accept num_3d_array as a parameter:
  # add code below here to create the numpy array, print it one row per line, then return it




# run your function with the list `[[1,2,3],[4,5,6],[7,8,9]]`
matrix_to_convert = [[1,2,3],[4,5,6],[7,8,9]]
actual = # add the call for the function here
# does it match the expected output?

---
### Exercise 4 - make a 2 x 2 x 2 numpy array

Write a function which will create a 2 x 2 x 2 array, then print the array one individual array per line.

Test data:

`[[[1,2],[3,4]],[[5,6],[7,8]]]`

Expected output:  
```
[1 2]
[3 4]
[5 6]
[7 8]
```

     

In [ ]:
import numpy as np

# add code below here for the function to create a 2x2x2 numpy array, including header and parameters



# run your function with the list [[[1,2],[3,4]],[[5,6],[7,8]]]
matrix_to_convert = [[[1,2],[3,4]],[[5,6],[7,8]]]
actual = # add the call for the function here
# does it match the expected output?

## Inspecting the shape of the array/matrix

numpy provides the `np.shape` property for reporting the shape of a numpy array.  np.shape will give the number of layers, rows, columns (and more if necessary) present in the array.  Arrays can be multi-dimensional but we will only arrays of maximum 3 dimensions to keep it simple.  

Example:  
```
matrix = np.array([[[1,1],[2,2],[3,3]],[[4,4],[5,5],[6,6]]])
print(matrix.shape)
```

Expected output:  
`(2, 3, 2)`

This matrix has 2 layers of 3 rows of 2 columns

---
### Exercise 5 - print the shape

Write a function which will:  
*  create a numpy array using the test data below
*  print the shape of the array

Test 1 data:  
`[3,7,56]`

Expected output:

`(3,)`

Test 2 data:  
`[[7,6,5,8,4,9],[3,7,5,8,6,9]]`

Expected output:  
`(2,6)`

In [ ]:
# add your code below here to import numpy, define the function and its parameter, create the numpy array from the parameter and return the shape



# run your function with the list [3,7,56]
list_to_convert = [3,7,56]
actual = <<your function name>>(list_to_convert)
print(actual)
# does it match the expected output?

# then run it again with the list [[7,6,5,8,4,9],[3,7,5,8,6,9]]
list_to_convert = [[7,6,5,8,4,9],[3,7,5,8,6,9]]
actual = <<your function name>>(list_to_convert)
print(actual)
# does it match the expected output?

---
### Exercise 6 - using slicing to print parts of arrays

Write a function which will:  
*  create an array from the Python list `[1,2,3,4,5]`
*  print the first 3 items in the array
*  print the last item in the array

Expected output:
```
[1 2 3]
5

```



In [ ]:
# add your code below here to import numpy, define the function and its parameter, create the numpy array from the parameter and print the first 3 and the last item



# run your function with the list [1,2,3,4,5]


# does it match the expected output?

---
### Exercise 7 - using slicing to print parts of array rows and columns

Write a function which will:  
*  create an array from the Python 2 dimensional list `[[1,2,3,4],[5,6,7,8],[9,1,2,3]]`
*  print the first item in the second row   
*  print the first 2 rows only
*  print the last 2 items in the last 2 rows

Expected output:  
```
5
[[1 2 3 4]
 [5 6 7 8]]
[[7 8]
 [2 3]]
```

  



In [ ]:
# add your code below here to import numpy, define the function and its parameter, create the numpy array from the parameter and print the requested data


# run your function with the list [[1,2,3,4],[5,6,7,8],[9,1,2,3]]


# does it match the expected output?

---
## Broadcasting an operation across an array

Because a numpy array is created from a related set of data, it is useful to be able to operate on every item in the array in the same way.  For instance, the array might hold a set of scores out of 30 and you might want to convert all scores into percentages.

We can do this in a number of ways:  
1.  Create a new array to store the result after the operation in the new array
```
scores = np.array([29,25,15,22,30])
percentages = scores / 30 * 100
print(percentages)
```
Expected output:
```
[ 96.66666667  83.33333333  50.          73.33333333 100.        ]
```
2.  Store the result in the original array
```
scores = np.array([29,25,15,22,30])
scores = scores / 30 * 100
print(scores)
```
Expected output:
```
[ 96.66666667  83.33333333  50.  73.33333333 100. ]
```

Give it a try:





---
### Exercise 8 - increase whole array by 20

Write a function which will:
*  create a numpy array of 12 numbers
*  create a new array adding 20 to each of the items in the first array  
*  print the new array

Test input:  
`[1,2,3,4,5,6,7,8,1,2,3,4]`

Expected output:  
`[21 22 23 24 25 26 27 28 21 22 23 24]`

---
## Using functions to create arrays of 1s, 0s or a range of numbers

You can use `np.arange(range)` to create an array with a range of numbers.  Like range in Python, either give 1 number to get all numbers from 0 to the number before it, or give 2 numbers to get the numbers from the first to one before the last.  You can specify the start number, the stop number and a step size (e.g. `(1,9,2)` will generate `[1 3 5 7]`:
```
array1 = np.arange(10)
```
will give array1 = `[0,1,2,3,4,5,6,7,8,9]`

```
array2 = np.arange(2,9)
```
will give array2 = `[2,3,4,5,6,7,8]`

```
array3 = np.arange(2,9,3)
```
will give array3 = `[2,5,8]`  

---

To create a new array of 10 zeros:
```
array4 = np.zeros(10)
```
will give array4 = `[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]`

To create a new array of 10 zeros as integers:
```
array5 = np.zeros(10, dtype='int32')
```
will give array5 = `[0 0 0 0 0 0 0 0 0 0]`

To create a new array of 8 ones:  
```
array6 = np.ones(8, dtype='int16')
```
will give array6 = `[1 1 1 1 1 1 1 1]`

---
### Exercise 9 - create a numpy array of the numbers 1 to 8  

Write a function which will:  
*  create a numpy array with the numbers 1 to 8 using `np.arange()`  
*  create a second numpy array with 12 zero integers
*  create a third numpy array with 4 ones (whole numbers)  
*  create a fourth numpy array with the the multiples of 10 from 10 to 100 (use arange with start, stop and step)

Expected output:  
```
[1 2 3 4 5 6 7 8]  
[0 0 0 0 0 0 0 0 0 0 0 0]  
[1 1 1 1]  
[ 10  20  30  40  50  60  70  80  90 100]
```


 

---
### Exercise 10 - create a numpy mask matrix

**Challenging**

Write a function which will create and print a numpy array as follows:

*  create **array1** with `shape=(8,8)` containing all zeros of dtype `int16`
*  print `array1`
*  find and print the number of rows and cols in array1
*  change the value of the corner items to `1`
*  print `array1`
*  change the value of the middle two items of the middle two rows of `array1`, each to `1` (use list indexing for this)
*  print `array1`

*Reference*: https://pythonexamples.org/python-numpy-zeros/

Expected output:  
```
[[0 0 0 0 0 0 0 0]  
 [0 0 0 0 0 0 0 0]  
 [0 0 0 0 0 0 0 0]  
 [0 0 0 0 0 0 0 0]  
 [0 0 0 0 0 0 0 0]  
 [0 0 0 0 0 0 0 0]  
 [0 0 0 0 0 0 0 0]  
 [0 0 0 0 0 0 0 0]]

 8,8

[[0 0 0 0 0 0 0 0]  
 [0 0 0 0 0 0 0 0]  
 [0 0 0 0 0 0 0 0]  
 [0 0 0 1 1 0 0 0]  
 [0 0 0 1 1 0 0 0]  
 [0 0 0 0 0 0 0 0]  
 [0 0 0 0 0 0 0 0]  
 [0 0 0 0 0 0 0 0]]

 [[1 0 0 0 0 0 0 1]  
 [0 0 0 0 0 0 0 0]  
 [0 0 0 0 0 0 0 0]  
 [0 0 0 1 1 0 0 0]  
 [0 0 0 1 1 0 0 0]  
 [0 0 0 0 0 0 0 0]  
 [0 0 0 0 0 0 0 0]  
 [1 0 0 0 0 0 0 1]] 
 ```



# Reflection
----

## What skills have you demonstrated in completing this notebook?

Your answer: 

## What caused you the most difficulty?

Your answer: 